name: CI Workflow for backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
      run:
        shell: bash
        working-directory: ./backend

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest     

    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm install

    - name: 'Run tests'
      run: npm run test


  lint:
    name: Run Linter
    runs-on: ubuntu-latest     

    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm install

    - name: 'Run Linter'
      run: npm run lint    
