name: CI Workflow for frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
      run:
        shell: bash
        working-directory: ./frontend

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest    

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x] 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: 'Install Dependencies'
      run: npm install

    - name: 'Run Linter'
      run: npm run lint   
